import '../../../domain/location/models/district_attraction.dart';
import '../../../domain/location/projection/control_mesh.dart';
import '../../../domain/location/projection/map_manifest.dart';

/// 台灣各行政區清單建構函式
List<AdministrativeDistrict> buildTaiwanAdministrativeDistricts(ControlMesh mesh) {
  final districtsData = [
    ('taipei', '台北市', 25.0375, 121.5637, 1.2),
    ('new_taipei', '新北市', 25.0116, 121.4658, 1.2),
    ('keelung', '基隆市', 25.1276, 121.7392, 1.2),
    ('taoyuan', '桃園市', 24.9936, 121.3010, 1.2),
    ('hsinchu', '新竹縣市', 24.8039, 120.9647, 1.2),
    ('miaoli', '苗栗縣', 24.5602, 120.8214, 1.2),
    ('taichung', '台中市', 24.1625, 120.6472, 1.2),
    ('changhua', '彰化縣', 24.0816, 120.5385, 1.2),
    ('nantou', '南投縣', 23.9610, 120.9719, 1.2),
    ('yunlin', '雲林縣', 23.7092, 120.4313, 1.2),
    ('chiayi', '嘉義縣市', 23.4800, 120.4491, 1.2),
    ('tainan', '台南市', 22.9997, 120.2025, 1.2),
    ('kaohsiung', '高雄市', 22.6273, 120.3014, 1.2),
    ('pingtung', '屏東縣', 22.5511, 120.5422, 1.2),
    ('yilan', '宜蘭縣', 24.7570, 121.7530, 1.2),
    ('hualien', '花蓮縣', 23.9872, 121.6016, 1.2),
    ('taitung', '台東縣', 22.7583, 121.1444, 1.2),
    ('penghu', '澎湖縣', 23.5711, 119.5793, 1.2),
  ];

  return [
    for (final (code, name, lat, lng, minZoom) in districtsData)
      AdministrativeDistrict(
        code: code,
        name: name,
        centerGeo: GeoPoint(lat, lng),
        centerPixel: mesh.projectToPixel(lat, lng),
        minZoomForSpots: minZoom,
      ),
  ];
}

/// 參考 Google Maps 熱門評價與推薦整理的台灣熱門觀光景點總庫
List<DistrictAttraction> buildTaiwanAttractionsCatalog(ControlMesh mesh) {
  // raw tuple: (id, title, districtCode, districtName, lat, lng, rating, reviews, category, desc, minZoom)
  final rawCatalog = <(
    String,
    String,
    String,
    String,
    double,
    double,
    double,
    int,
    AttractionCategory,
    String,
    double
  )>[
    // ==========================================
    // 1. 台北市 (Taipei)
    // ==========================================
    (
      'tp_101',
      '台北101觀景台',
      'taipei',
      '台北市',
      25.0339,
      121.5645,
      4.6,
      89200,
      AttractionCategory.landmark,
      '台灣最具代表性的超高摩天大樓，能俯瞰整座台北盆地璀璨天際線。',
      0.5,
    ),
    (
      'tp_palace_museum',
      '國立故宮博物院',
      'taipei',
      '台北市',
      25.1024,
      121.5485,
      4.6,
      52100,
      AttractionCategory.culture,
      '典藏近七十萬件中華歷代皇家珍品，被譽為世界四大博物館之一。',
      0.5,
    ),
    (
      'tp_cksmh',
      '中正紀念堂',
      'taipei',
      '台北市',
      25.0347,
      121.5218,
      4.6,
      68400,
      AttractionCategory.landmark,
      '藍白相間八角殿堂與宏偉自由廣場牌樓，衛兵交接儀式是國際旅客必訪。',
      1.2,
    ),
    (
      'tp_yangmingshan',
      '陽明山小油坑',
      'taipei',
      '台北市',
      25.1758,
      121.5442,
      4.6,
      45300,
      AttractionCategory.nature,
      '後火山作用形成的噴氣孔與硫磺結晶，秋季滿山芒草與春櫻盛開。',
      1.5,
    ),
    (
      'tp_elephant_mountain',
      '象山親山步道',
      'taipei',
      '台北市',
      25.0274,
      121.5756,
      4.6,
      31800,
      AttractionCategory.nature,
      '眺望台北101與台北市區全景的首選步道，夕陽與夜景享譽全球。',
      1.8,
    ),
    (
      'tp_songshan_cultural',
      '松山文創園區',
      'taipei',
      '台北市',
      25.0441,
      121.5606,
      4.5,
      41200,
      AttractionCategory.culture,
      '前身為日治時期松山菸廠，保留古色古香巴洛克花園與現代文創市集。',
      1.8,
    ),
    (
      'tp_lungshan_temple',
      '艋舺龍山寺',
      'taipei',
      '台北市',
      25.0368,
      121.4999,
      4.6,
      38600,
      AttractionCategory.culture,
      '建於清乾隆年間的國定古蹟，精美石雕剪黏與月老靈驗遠近馳名。',
      2.0,
    ),
    (
      'tp_beitou_hotspring',
      '北投溫泉博物館',
      'taipei',
      '台北市',
      25.1365,
      121.5074,
      4.5,
      22400,
      AttractionCategory.recreation,
      '英國都鐸式紅磚洋樓，曾是東亞最大的公共溫泉浴場，洋溢大正浪漫。',
      2.2,
    ),

    // ==========================================
    // 2. 新北市 (New Taipei)
    // ==========================================
    (
      'ntp_jiufen',
      '九份老街',
      'new_taipei',
      '新北市',
      25.1088,
      121.8452,
      4.4,
      76500,
      AttractionCategory.culture,
      '依山而建的黃金山城，紅燈籠石階、芋圓美食與極致山海景致。',
      0.5,
    ),
    (
      'ntp_shifen_waterfall',
      '十分瀑布',
      'new_taipei',
      '新北市',
      25.0494,
      121.7876,
      4.5,
      39400,
      AttractionCategory.nature,
      '台灣最大簾幕型瀑布，有「台灣尼加拉瀑布」美名，水氣蒸騰常現彩虹。',
      1.2,
    ),
    (
      'ntp_yehliu',
      '野柳地質公園',
      'new_taipei',
      '新北市',
      25.2063,
      121.6906,
      4.5,
      44100,
      AttractionCategory.nature,
      '大自然鬼斧神工雕琢出的蕈狀岩，「女王頭」為享譽國際的地質奇觀。',
      1.5,
    ),
    (
      'ntp_tamsui_wharf',
      '淡水漁人碼頭',
      'new_taipei',
      '新北市',
      25.1834,
      121.4116,
      4.5,
      48200,
      AttractionCategory.sightseeing,
      '白色風帆造形的情人橋，漫步木棧道欣賞全台著名的「淡水暮色」。',
      1.5,
    ),
    (
      'ntp_sanxia_old_street',
      '三峽老街',
      'new_taipei',
      '新北市',
      24.9338,
      121.3703,
      4.4,
      28900,
      AttractionCategory.food,
      '紅磚連棟拱廊與巴洛克立面，金牛角麵包與清水祖師廟雕刻聖地。',
      2.0,
    ),
    (
      'ntp_wulai_waterfall',
      '烏來瀑布與台車',
      'new_taipei',
      '新北市',
      24.8491,
      121.5512,
      4.4,
      26300,
      AttractionCategory.recreation,
      '泰雅族原民文化、清澈野溪溫泉，搭乘復古台車欣賞絹秀高聳的烏來瀑布。',
      2.2,
    ),

    // ==========================================
    // 3. 基隆市 (Keelung)
    // ==========================================
    (
      'kl_heping_island',
      '和平島地質公園',
      'keelung',
      '基隆市',
      25.1611,
      121.7644,
      4.5,
      27300,
      AttractionCategory.nature,
      '天然海蝕豆腐岩與天然海水泳池，眺望基隆嶼與無垠蔚藍海景。',
      1.5,
    ),
    (
      'kl_zhengbin_port',
      '正濱漁港彩色屋',
      'keelung',
      '基隆市',
      25.1528,
      121.7681,
      4.3,
      19800,
      AttractionCategory.sightseeing,
      '繽紛彩繪水岸宛如台版威尼斯，基隆最熱門的社群美照打卡熱點。',
      1.8,
    ),
    (
      'kl_chaojing_park',
      '潮境公園飛天掃帚',
      'keelung',
      '基隆市',
      25.1436,
      121.8039,
      4.5,
      23500,
      AttractionCategory.recreation,
      '面臨美麗的海灣，巨大的裝置藝術「飛天掃帚」有如進入哈利波特魔法世界。',
      2.0,
    ),

    // ==========================================
    // 4. 桃園市 (Taoyuan)
    // ==========================================
    (
      'ty_daxi_old_street',
      '大溪老街',
      'taoyuan',
      '桃園市',
      24.8844,
      121.2872,
      4.4,
      52700,
      AttractionCategory.food,
      '精雕細琢的日治巴洛克街屋，百年黑豆干與木藝工藝聞名全台。',
      1.2,
    ),
    (
      'ty_xpark',
      'Xpark 都會水族館',
      'taoyuan',
      '桃園市',
      25.0183,
      121.2144,
      4.4,
      38500,
      AttractionCategory.recreation,
      '來自日本八景島的新世代沉浸式水族館，夢幻癒見水母與企鵝奇幻咖啡館。',
      1.5,
    ),
    (
      'ty_shimen_reservoir',
      '石門水庫風景區',
      'taoyuan',
      '桃園市',
      24.8136,
      121.2464,
      4.4,
      33200,
      AttractionCategory.nature,
      '北台灣水資源重鎮，壯麗洩洪景觀與周邊名聞遐邇的活魚三吃美食。',
      1.8,
    ),

    // ==========================================
    // 5. 新竹縣市 (Hsinchu)
    // ==========================================
    (
      'hc_city_god_temple',
      '新竹都城隍廟',
      'hsinchu',
      '新竹縣市',
      24.8042,
      120.9664,
      4.4,
      34600,
      AttractionCategory.food,
      '全台位階最高城隍廟，廟埕小吃聚集新竹米粉、貢丸與紅糟肉圓。',
      1.2,
    ),
    (
      'hc_smangus',
      '司馬庫斯神木群',
      'hsinchu',
      '新竹縣市',
      24.5794,
      121.3325,
      4.7,
      12800,
      AttractionCategory.nature,
      '深山中的泰雅族部落，有「上帝的部落」之稱，巨木群步道氣勢磅礴。',
      1.8,
    ),
    (
      'hc_leofoo_village',
      '六福村主題遊樂園',
      'hsinchu',
      '新竹縣市',
      24.8256,
      121.1814,
      4.5,
      46800,
      AttractionCategory.recreation,
      '結合非洲野生動物園與美墨奇幻主題的複合型大型遊樂園。',
      1.8,
    ),
    (
      'hc_nanliao_coast',
      '南寮漁港魚鱗天梯',
      'hsinchu',
      '新竹縣市',
      24.8492,
      120.9272,
      4.4,
      29400,
      AttractionCategory.sightseeing,
      '新竹17公里海岸線起點，階梯式消波塊形如魚鱗，是吹海風賞落日勝地。',
      2.2,
    ),

    // ==========================================
    // 6. 苗栗縣 (Miaoli)
    // ==========================================
    (
      'ml_shengxing_station',
      '勝興車站與舊山線',
      'miaoli',
      '苗栗縣',
      24.3875,
      120.7814,
      4.4,
      32500,
      AttractionCategory.culture,
      '西部鐵道最高點日式木造車站，搭乘鐵道自行車 Rail Bike 穿越綠蔭隧道。',
      1.5,
    ),
    (
      'ml_longteng_bridge',
      '龍騰斷橋',
      'miaoli',
      '苗栗縣',
      24.3583,
      120.7742,
      4.3,
      21800,
      AttractionCategory.culture,
      '歷經關刀山大地震不屈屹立的糯米紅磚拱橋遺跡，殘缺而優雅的美學。',
      1.8,
    ),
    (
      'ml_baishatun',
      '白沙屯拱天宮',
      'miaoli',
      '苗栗縣',
      24.5703,
      120.7131,
      4.8,
      35200,
      AttractionCategory.culture,
      '香火極盛的媽祖信仰中心，「粉紅超跑」無固定路線進香享譽全台。',
      1.8,
    ),

    // ==========================================
    // 7. 台中市 (Taichung)
    // ==========================================
    (
      'tc_opera_house',
      '台中國家歌劇院',
      'taichung',
      '台中市',
      24.1628,
      120.6404,
      4.6,
      48900,
      AttractionCategory.landmark,
      '伊東豊雄操刀的世界級無樑柱曲牆美聲涵洞建築，七期都會核心地標。',
      0.5,
    ),
    (
      'tc_gaomei_wetland',
      '高美濕地天空之鏡',
      'taichung',
      '台中市',
      24.3122,
      120.5503,
      4.6,
      62800,
      AttractionCategory.nature,
      '一望無際的泥灘地與高聳白色風車，夕陽倒影被譽為台灣最美天空之鏡。',
      1.2,
    ),
    (
      'tc_rainbow_village',
      '彩虹眷村',
      'taichung',
      '台中市',
      24.1336,
      120.6100,
      4.4,
      42600,
      AttractionCategory.culture,
      '彩虹爺爺一筆一畫手繪出的童趣繽紛世界，曾登英國 BBC 與 Lonely Planet。',
      1.5,
    ),
    (
      'tc_audit_village',
      '審計新村文創聚落',
      'taichung',
      '台中市',
      24.1453,
      120.6631,
      4.4,
      39800,
      AttractionCategory.sightseeing,
      '舊審計處員工宿舍改建的青年創業基地，假日文創市集人潮絡繹不絕。',
      1.8,
    ),
    (
      'tc_miyahara',
      '宮原眼科冰淇淋',
      'taichung',
      '台中市',
      24.1378,
      120.6833,
      4.4,
      43200,
      AttractionCategory.food,
      '日治眼科診所蛻變為哈利波特霍格華茲風挑高洋樓，鳳梨酥與冰品旗艦殿堂。',
      2.0,
    ),
    (
      'tc_wuling_farm',
      '武陵農場',
      'taichung',
      '台中市',
      24.3581,
      121.3114,
      4.6,
      25600,
      AttractionCategory.nature,
      '雪霸國家公園深山谷地，初春粉紅櫻花海與七家灣溪國寶櫻花鉤吻鮭。',
      2.2,
    ),

    // ==========================================
    // 8. 彰化縣 (Changhua)
    // ==========================================
    (
      'ch_lukang_old_street',
      '鹿港天后宮與老街',
      'changhua',
      '彰化縣',
      24.0572,
      120.4314,
      4.5,
      58400,
      AttractionCategory.culture,
      '「一府二鹿三艋舺」的輝煌古鎮，紅磚古巷九曲巷與香火鼎盛天后宮。',
      1.2,
    ),
    (
      'ch_baguashan',
      '八卦山大佛風景區',
      'changhua',
      '彰化縣',
      24.0792,
      120.5483,
      4.3,
      29800,
      AttractionCategory.landmark,
      '高達22公尺的黑色如來大佛慈航普渡，天空步道穿梭山林俯瞰彰化市區。',
      1.5,
    ),
    (
      'ch_roundhouse',
      '彰化扇形車庫',
      'changhua',
      '彰化縣',
      24.0853,
      120.5392,
      4.5,
      26100,
      AttractionCategory.culture,
      '台灣唯一保存完整的扇形鐵路車庫，12股道旋轉盤見證蒸汽老火車風采。',
      1.8,
    ),

    // ==========================================
    // 9. 南投縣 (Nantou)
    // ==========================================
    (
      'nt_sun_moon_lake',
      '日月潭國家風景區',
      'nantou',
      '南投縣',
      23.8583,
      120.9164,
      4.7,
      82600,
      AttractionCategory.nature,
      '群山環抱的天然明珠湖泊，環潭自行車道曾獲 CNN 評為世界十大最美。',
      0.5,
    ),
    (
      'nt_cingjing_farm',
      '清境農場青青草原',
      'nantou',
      '南投縣',
      24.0583,
      121.1622,
      4.5,
      51800,
      AttractionCategory.nature,
      '綿延綠草坡與北歐風城堡，可愛綿羊秀與天空步道宛如置身歐洲阿爾卑斯。',
      1.2,
    ),
    (
      'nt_zinan_temple',
      '竹山紫南宮',
      'nantou',
      '南投縣',
      23.8183,
      120.7222,
      4.7,
      56700,
      AttractionCategory.culture,
      '求發財金祈福傳奇聖地，七星級金筍造型公廁更是全國知名景點。',
      1.5,
    ),
    (
      'nt_xitou_forest',
      '溪頭自然教育園區',
      'nantou',
      '南投縣',
      23.6733,
      120.7964,
      4.5,
      34900,
      AttractionCategory.nature,
      '漫步柳杉林海中的空中走廊與大學池竹橋，豐富芬多精與松鼠生態。',
      1.8,
    ),
    (
      'nt_checheng_village',
      '車埕木業山城',
      'nantou',
      '南投縣',
      23.8331,
      120.8664,
      4.5,
      28300,
      AttractionCategory.culture,
      '集集鐵道支線最後終點站，依山傍水的貯木池與林班道日式建築群。',
      2.2,
    ),

    // ==========================================
    // 10. 雲林縣 (Yunlin)
    // ==========================================
    (
      'yl_chaotian_temple',
      '北港朝天宮',
      'yunlin',
      '雲林縣',
      23.5681,
      120.3042,
      4.7,
      46900,
      AttractionCategory.culture,
      '台灣媽祖信仰的重要源頭，國定古蹟建築精湛，周邊北港大餅與鴨肉羹。',
      1.2,
    ),
    (
      'yl_janfusun',
      '劍湖山世界主題樂園',
      'yunlin',
      '雲林縣',
      23.6181,
      120.5794,
      4.3,
      31400,
      AttractionCategory.recreation,
      '中台灣指標遊樂園，飛天潛艇 G5 與彩虹摩天輪俯瞰嘉南平原。',
      1.8,
    ),
    (
      'yl_xiluo_bridge',
      '西螺大橋跨河景觀',
      'yunlin',
      '雲林縣',
      23.8053,
      120.4603,
      4.4,
      19400,
      AttractionCategory.landmark,
      '橫跨濁水溪的鋼構紅色巨桁，曾為遠東第一長橋，落日餘暉格外耀眼。',
      2.0,
    ),

    // ==========================================
    // 11. 嘉義縣市 (Chiayi)
    // ==========================================
    (
      'cy_alishan',
      '阿里山森林遊樂區',
      'chiayi',
      '嘉義縣市',
      23.5103,
      120.8033,
      4.7,
      64200,
      AttractionCategory.nature,
      '五奇絕景：日出、雲海、鐵路、森林與晚霞，神木群森呼吸。',
      0.5,
    ),
    (
      'cy_hinoki_village',
      '檜意森活村',
      'chiayi',
      '嘉義縣市',
      23.4864,
      120.4542,
      4.4,
      45800,
      AttractionCategory.culture,
      '全台灣保存最完整的日式檜木官舍群，穿著和服穿梭文創庭園。',
      1.2,
    ),
    (
      'cy_southern_palace',
      '故宮南院',
      'chiayi',
      '嘉義縣市',
      23.4614,
      120.2931,
      4.5,
      32800,
      AttractionCategory.culture,
      '融合中國水墨虛實意象的現代流線建築，周邊湖光水舞相映成趣。',
      1.8,
    ),

    // ==========================================
    // 12. 台南市 (Tainan)
    // ==========================================
    (
      'tn_chimei_museum',
      '奇美博物館',
      'tainan',
      '台南市',
      22.9347,
      120.2261,
      4.7,
      68900,
      AttractionCategory.culture,
      '希臘羅馬神話宮殿建築與阿波羅噴泉，典藏西洋古典藝術、名琴與兵器。',
      1.2,
    ),
    (
      'tn_anping_fort',
      '安平古堡與老街',
      'tainan',
      '台南市',
      22.9997,
      120.1603,
      4.4,
      54300,
      AttractionCategory.culture,
      '建於1624年的荷蘭熱蘭遮城紅磚殘壁，台灣歷史開端的象徵地標。',
      1.2,
    ),
    (
      'tn_chihkan_tower',
      '赤崁樓',
      'tainan',
      '台南市',
      22.9975,
      120.2025,
      4.4,
      42100,
      AttractionCategory.culture,
      '昔稱普羅民遮城，九座贔屭御碑與紅樓飛簷，夜間點燈更添典雅古意。',
      0.5,
    ),
    (
      'tn_salt_field',
      '井仔腳瓦盤鹽田',
      'tainan',
      '台南市',
      23.2592,
      120.1083,
      4.5,
      28400,
      AttractionCategory.sightseeing,
      '北門現存最古老瓦盤鹽田，一座座雪白小鹽丘在落日夕照下如夢似幻。',
      1.8,
    ),
    (
      'tn_shennong_street',
      '神農街復古文創街',
      'tainan',
      '台南市',
      22.9981,
      120.1972,
      4.4,
      31500,
      AttractionCategory.food,
      '台南老屋文創代名詞，夜晚懸掛溫暖燈籠，老酒吧與文青工坊林立。',
      2.0,
    ),

    // ==========================================
    // 13. 高雄市 (Kaohsiung)
    // ==========================================
    (
      'kh_85_tower',
      '高雄85大樓',
      'kaohsiung',
      '高雄市',
      22.6114,
      120.3003,
      4.3,
      28900,
      AttractionCategory.landmark,
      '高聳入雲的高雄港都地標，特殊「高」字型設計見證海港繁華年代。',
      0.5,
    ),
    (
      'kh_pier2',
      '駁二藝術特區',
      'kaohsiung',
      '高雄市',
      22.6203,
      120.2822,
      4.6,
      72400,
      AttractionCategory.culture,
      '舊港口碼頭倉庫化身當代文創聚落，大義倉庫、輕軌穿梭與海風雕塑。',
      1.2,
    ),
    (
      'kh_cijin_island',
      '旗津老街與旗后燈塔',
      'kaohsiung',
      '高雄市',
      22.6153,
      120.2672,
      4.4,
      49800,
      AttractionCategory.food,
      '搭渡輪前往海島品嚐海鮮老街，純白燈塔咖啡廳遠眺西子灣浪潮。',
      1.5,
    ),
    (
      'kh_dragon_tiger_pagoda',
      '蓮池潭龍虎塔',
      'kaohsiung',
      '高雄市',
      22.6811,
      120.2922,
      4.4,
      36700,
      AttractionCategory.sightseeing,
      '湖畔色彩奪目的七層雙塔，「入龍喉、出虎口」消災解厄享譽國際。',
      1.8,
    ),
    (
      'kh_foguanshan',
      '佛光山佛陀紀念館',
      'kaohsiung',
      '高雄市',
      22.7564,
      120.4431,
      4.7,
      45100,
      AttractionCategory.culture,
      '高達108公尺的巍峨銅鑄大佛與八座宏偉寶塔，莊嚴壯闊的佛教聖地。',
      2.0,
    ),

    // ==========================================
    // 14. 屏東縣 (Pingtung)
    // ==========================================
    (
      'pt_eluanbi',
      '鵝鑾鼻燈塔公園',
      'pingtung',
      '屏東縣',
      21.9022,
      120.8525,
      4.5,
      42700,
      AttractionCategory.landmark,
      '台灣最南端純白燈塔，號稱東亞之光，藍天碧草與珊瑚礁海蝕奇景。',
      0.5,
    ),
    (
      'pt_nmmba',
      '國立海洋生物博物館',
      'pingtung',
      '屏東縣',
      22.0464,
      120.6983,
      4.7,
      61900,
      AttractionCategory.recreation,
      '亞洲最大的水族海洋館之一，漫步巨型海底隧道，夜宿海生館奇趣無比。',
      1.2,
    ),
    (
      'pt_baishawan',
      '墾丁白沙灣海灘',
      'pingtung',
      '屏東縣',
      21.9344,
      120.7183,
      4.5,
      29400,
      AttractionCategory.nature,
      '潔白細緻的貝殼砂海灘，《少年PI的奇幻漂流》取景地，南國渡假天堂。',
      1.8,
    ),
    (
      'pt_vase_rock',
      '小琉球花瓶岩',
      'pingtung',
      '屏東縣',
      22.3542,
      120.3803,
      4.6,
      24700,
      AttractionCategory.nature,
      '珊瑚礁受海水侵蝕形成的柱狀岩，周邊海水澄澈，常可近距離遇見海龜。',
      2.0,
    ),

    // ==========================================
    // 15. 宜蘭縣 (Yilan)
    // ==========================================
    (
      'yl_tangweigou',
      '礁溪湯圍溝溫泉公園',
      'yilan',
      '宜蘭縣',
      24.8303,
      121.7761,
      4.4,
      44200,
      AttractionCategory.recreation,
      '天然碳酸氫鈉泉裊裊升煙，免費戶外泡腳池與溫泉魚咬腳樂趣。',
      1.2,
    ),
    (
      'yl_lanyang_museum',
      '蘭陽博物館與烏石港',
      'yilan',
      '宜蘭縣',
      24.8692,
      121.8331,
      4.5,
      37800,
      AttractionCategory.culture,
      '融入東北角單面山地貌的斜三角前衛建築，烏石港也是賞鯨船出發地。',
      1.5,
    ),
    (
      'yl_luodong_forestry',
      '羅東林業文化園區',
      'yilan',
      '宜蘭縣',
      24.6853,
      121.7722,
      4.5,
      36500,
      AttractionCategory.nature,
      '過去太平山林場木材集散地，整修水上貯木池、復古蒸汽火車與環湖木棧道。',
      1.8,
    ),
    (
      'yl_center_traditional_arts',
      '國立傳統藝術中心',
      'yilan',
      '宜蘭縣',
      24.6972,
      121.8242,
      4.5,
      46800,
      AttractionCategory.culture,
      '仿古老街復刻民藝大街，傳統布袋戲、捏麵人與歌仔戲熱鬧傳承。',
      2.0,
    ),
    (
      'yl_taipingshan',
      '太平山見晴懷古步道',
      'yilan',
      '宜蘭縣',
      24.4922,
      121.5361,
      4.7,
      31400,
      AttractionCategory.nature,
      '被 CNN 評選為全球最美28條小路之一，青苔鐵道被繚繞白霧擁抱。',
      2.2,
    ),

    // ==========================================
    // 16. 花蓮縣 (Hualien)
    // ==========================================
    (
      'hl_taroko',
      '太魯閣國家公園',
      'hualien',
      '花蓮縣',
      24.1583,
      121.6022,
      4.7,
      67800,
      AttractionCategory.nature,
      '立霧溪千萬年沖刷出震撼世界的大理石峽谷，燕子口與九曲洞巧奪天工。',
      0.5,
    ),
    (
      'hl_qixingtan',
      '七星潭月牙灣海岸',
      'hualien',
      '花蓮縣',
      24.0322,
      121.6303,
      4.6,
      52900,
      AttractionCategory.nature,
      '弧形礫石海灣，浪花拍打鵝卵石發出清脆聲響，遠眺清水斷崖壯麗山海。',
      1.2,
    ),
    (
      'hl_qingshui_cliff',
      '清水斷崖絕壁奇景',
      'hualien',
      '花蓮縣',
      24.2083,
      121.6731,
      4.7,
      38600,
      AttractionCategory.nature,
      '蘇花公路上的險峻奇蹟，近千公尺懸崖筆直插入碧藍太平洋。',
      1.5,
    ),
    (
      'hl_dongdamen',
      '花蓮東大門夜市',
      'hualien',
      '花蓮縣',
      23.9744,
      121.6133,
      4.4,
      49500,
      AttractionCategory.food,
      '四大特色街區匯集400家攤商，原住民石板烤肉與在地風味匯聚。',
      1.8,
    ),
    (
      'hl_farglory_ocean',
      '遠雄海洋公園',
      'hualien',
      '花蓮縣',
      23.9014,
      121.6025,
      4.4,
      36200,
      AttractionCategory.recreation,
      '坐落太平洋左岸的國際級海洋樂園，空中纜車與海豚躍浪精彩絕倫。',
      2.0,
    ),

    // ==========================================
    // 17. 台東縣 (Taitung)
    // ==========================================
    (
      'tt_mr_brown_avenue',
      '伯朗大道金城武樹',
      'taitung',
      '台東縣',
      23.1003,
      121.2131,
      4.5,
      46500,
      AttractionCategory.sightseeing,
      '無任何電線桿干擾的純粹稻田公路，微風吹拂稻浪金黃翻騰。',
      1.2,
    ),
    (
      'tt_sanxiantai',
      '三仙台跨海八拱橋',
      'taitung',
      '台東縣',
      23.1233,
      121.4042,
      4.5,
      38900,
      AttractionCategory.nature,
      '如巨龍波浪般橫跨大海的八拱跨海步橋，東海岸看日出第一勝地。',
      1.5,
    ),
    (
      'tt_duoliang_station',
      '多良車站海天月台',
      'taitung',
      '台東縣',
      22.5072,
      120.9603,
      4.2,
      34800,
      AttractionCategory.sightseeing,
      '紅色鐵欄杆緊臨太平洋，火車奔馳出山洞時海天一色的極致名場面。',
      1.8,
    ),
    (
      'tt_taitung_forest_park',
      '台東黑森林琵琶湖',
      'taitung',
      '台東縣',
      22.7603,
      121.1572,
      4.6,
      32900,
      AttractionCategory.nature,
      '防風木麻黃森林環繞的地下湧泉湖，水清如鏡倒映藍天與水草。',
      2.0,
    ),
    (
      'tt_zhiben_hotspring',
      '知本溫泉風景區',
      'taitung',
      '台東縣',
      22.6942,
      120.9972,
      4.4,
      22600,
      AttractionCategory.recreation,
      '全台知名優質碳酸氫鈉弱鹼泉，水質清澈無色，潤膚美肌東台第一湯。',
      2.2,
    ),

    // ==========================================
    // 18. 澎湖縣 (Penghu)
    // ==========================================
    (
      'ph_moses_parting_sea',
      '奎壁山摩西分海',
      'penghu',
      '澎湖縣',
      23.5972,
      119.6731,
      4.6,
      28400,
      AttractionCategory.nature,
      '潮汐退潮時海水緩緩退開，露出玄武岩石礫步道直通赤嶼的奇觀。',
      1.5,
    ),
    (
      'ph_great_bridge',
      '澎湖跨海大橋',
      'penghu',
      '澎湖縣',
      23.6522,
      119.5442,
      4.4,
      31800,
      AttractionCategory.landmark,
      '連接白沙與西嶼的白色長虹大橋，跨越咆哮海峽的澎湖知名精神標誌。',
      1.8,
    ),
    (
      'ph_twin_heart_weir',
      '七美雙心石滬',
      'penghu',
      '澎湖縣',
      23.2183,
      119.4442,
      4.5,
      21900,
      AttractionCategory.culture,
      '利用潮差捕魚的先人古老智慧，浪漫心心相印的玄武岩石滬永恆地景。',
      2.2,
    ),
  ];

  return [
    for (final (
          id,
          title,
          distCode,
          distName,
          lat,
          lng,
          rating,
          reviews,
          category,
          desc,
          minZoom,
        ) in rawCatalog)
      DistrictAttraction(
        id: id,
        title: title,
        districtCode: distCode,
        districtName: distName,
        geo: GeoPoint(lat, lng),
        pixel: mesh.projectToPixel(lat, lng),
        rating: rating,
        reviewCount: reviews,
        category: category,
        description: desc,
        minZoom: minZoom,
      ),
  ];
}
